### ISSUE TITLE
[BUG] Some error has occurred. Check your network and use correct URL

### ISSUE THREAD

**Issue by VoltageCatYT** [aandrew-me/ytDownloader#158]
**Bug Description**
URL: https://youtube.com/playlist?list=PLODe67L10pIyyaajN9SkQZIjdWt6Dkl1B&si=EQEF1yMrbCQJCkAO

`Traceback (most recent call last): File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main return _run_code(code, main_globals, None, File "/usr/lib/python3.10/runpy.py", line 86, in _run_code exec(code, run_globals) File "/home/soto/.ytDownloader/ytdlp/__main__.py", line 17, in File "/home/soto/.ytDownloader/ytdlp/yt_dlp/__init__.py", line 1008, in main File "/home/soto/.ytDownloader/ytdlp/yt_dlp/__init__.py", line 962, in _real_main File "/home/soto/.ytDownloader/ytdlp/yt_dlp/YoutubeDL.py", line 767, in __init__ File "/home/soto/.ytDownloader/ytdlp/yt_dlp/YoutubeDL.py", line 3997, in _setup_opener File "/home/soto/.ytDownloader/ytdlp/yt_dlp/cookies.py", line 106, in load_cookies File "/home/soto/.ytDownloader/ytdlp/yt_dlp/cookies.py", line 127, in extract_cookies_from_browser File "/home/soto/.ytDownloader/ytdlp/yt_dlp/cookies.py", line 288, in _extract_chrome_cookies FileNotFoundError: could not find chrome cookies database in "/home/soto/.var/app/io.github.aandrew_me.ytdn/config/google-chrome"
`

**Screenshots**
![Screenshot 2023-08-29 9 08 57 PM](https://github.com/aandrew-me/ytDownloader/assets/75049520/9f760764-d2c1-4431-b7b7-87e6c21bebce)

 - Operating system: Linux Debian 11
 - App version: 3.14.2
 - Package version (flatpak/snap/other): flatpak

**Comment by VoltageCatYT** [comment]
I was doing something wrong I didn't click that icon on the upper right corner,  Make sure to press "download playlist" if you want to download batch videos, that mistake on my end
