### ISSUE TITLE
Need help building locally

### ISSUE THREAD

**Issue by Muxutruk2** [aandrew-me/ytDownloader#208]
The command "npm start linux" gives me this error

```
ytdownloader@3.17.4 linux
electron-builder -l


Error: Cannot find module 'fs/promises'
Require stack:
- [my folders...]/ytDownloader/node_modules/builder-util/out/fs.js
- [my folders...]/ytDownloader/node_modules/builder-util/out/util.js
- [my folders...]/ytDownloader/node_modules/electron-builder/out/cli/cli.js
- [my folders...]/ytDownloader/node_modules/electron-builder/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> ([my folders...]/ytDownloader/node_modules/builder-util/src/fs.ts:5:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> ([my folders...]/ytDownloader/node_modules/builder-util/src/util.ts:25:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)

at Function.Module._load (internal/modules/cjs/loader.js:708:14)
 ```    

It's clearly saying that fs/promises is missing, but it is listed in package.json and i tried installing manually and gave no errors. Is this a typo and instead of "fs/promises" it should be "fs.promisies"

Thanks in advance

**Comment by aandrew-me** [comment]
Did you read the build instruction in the readme?

**Comment by Muxutruk2** [comment]
> Did you read the build instruction in the readme?

Yes, i did, i followed every step, now i will try to start from scratch and remove everything to see if that is the problem

**Comment by aandrew-me** [comment]
But there is no `npm start linux` command there.
To install dependencies you need to run `npm i`
Then you can Run the program without even building it with `npm start`

**Comment by Muxutruk2** [comment]
Ok i reinstalled everything, installed electron and it opens, i do `npm start` and it opens, thanks
